version: '3'
services:
 nexus:
  image: sonatype/nexus3
  container_name: nexus
  ports:
    - "8081:8081"
 jenkins:
  image: "jenkins/jenkins:latest"
  ports:
    - "8080:8080"
    - "50000:50000"
  volumes:
    - "./jenkins:/var/jenkins_home"
volumes:
 nexus-data: {}
